name: lp
channels:
  - conda-forge
dependencies:
  - python=3.11.*
  - numpy
  - scipy
  - matplotlib
  - pyyaml
  - nptdms
  - pytest
  - pytest-qt
  - pytest-mock
  - spyder
  - git
  - make
  - pip
  - pip:
    - auto-py-to-exe
