name: lp-dev-win7
channels:
  - conda-forge
dependencies:
  - python=3.7.9
  - numpy
  - scipy
  - matplotlib
  - pyyaml
  - spyder
  - pip
  - pytest
  - pytest-mock
  - pytest-qt
  - git
  - make
  - pip:
    - nptdms==1.6.0
    - auto-py-to-exe
