name: lp-win7-pytest
channels:
  - conda-forge
dependencies:
  - python=3.7.9
  - numpy
  - scipy
  - matplotlib
  - pyyaml
  - pip
  - pytest
  - pytest-mock
  - pytest-qt
  - pip:
    - nptdms==1.6.0
    - auto-py-to-exe
